### ISSUE TITLE
Allow Traversables not just arrays

### ISSUE THREAD

**Issue by sagikazarmark** [th3n3rd/cartesian-product#1]
It would be awesome if the library could support Traversables as well, not just arrays.

**Comment by th3n3rd** [comment]
I thought about that, letting a Traversable object be accepted will still need to be casted into an array unless we specifically expect an Iterator and not a general Traversable. What do you think?

**Comment by sagikazarmark** [comment]
Actually I would do the following:

1. Accept `Traversable`s and `array`s
2. Wrap array in `ArrayIterator`s and `Traversable`s in `IteratorIterator`s

You would save yourself a lot of work (and tests) if you would extend `IteratorIterator` in `Set` as well.

**Comment by sagikazarmark** [comment]
Actually I started to work on an implementation, which is quite similar to yours. I am going to submit a PR.

**Comment by th3n3rd** [comment]
Go ahead then.

**Comment by sagikazarmark** [comment]
Awesome, thanks. ;)
