### ISSUE TITLE
Arrays as items must be wrapped in an extra array

### ISSUE THREAD

**Issue by sagikazarmark** [th3n3rd/cartesian-product#6]
I have the following data set:

``` php
[
	'methods' => ['GET', 'POST', 'PUT'],
	'uri' => ['uri'],
	'headers' => [
		[],
		[
			'Content-Type' => 'text/html'
		]
	],
]
```

For some reasons the headers array is getting merged into the main product unless I wrap them into an extra array.

I think it is because of [this](https://github.com/th3n3rd/cartesian-product/blob/master/src/Set.php#L44) check.

Can you confirm that?

**Comment by th3n3rd** [comment]
I am not quite sure on how you inject those values, but in general It all depends on what is your expected result. That check is handling the "last neighbour" case where the result could potentially be a non-array (not able to merge) value, that was only because I was using array internally.

**Comment by sagikazarmark** [comment]
Actually it is not the last neighbour, there are some sets after headers, just didn't put them in the example. I think that sub-arrays should always be treated as values as one, they should not be merged or something.

I would do the following:
1. The last neighbour (namely the neighbour which is not a `Set`) should ALWAYS be wrapped in an array.
2. The current value should ALWAYS be wrapped in an array and merged with the previous value (which must definitely be an array).
3. Array check can be removed from CertasianProduct since set will always return one.

**Comment by sagikazarmark** [comment]
The problem is that check is only done when the item is not an array. So that the returned value must be an array, if it is then there is a problem, because I want to get that array back as a value, not merged into the array.

**Comment by th3n3rd** [comment]
Yeah I got what you meant. I am going to merge your PR.

**Comment by sagikazarmark** [comment]
Thanks

**Comment by sagikazarmark** [comment]
Maybe a new tag would be appropriate

**Comment by th3n3rd** [comment]
Yeah I am doing it :)

**Comment by sagikazarmark** [comment]
Thanks :+1:
